[package]
name = "tracedraw"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TraceDraw: an open-source vector illustration editor"

[[bin]]
name = "tracedraw"
path = "src/main.rs"

[dependencies]
tracedraw-core.workspace = true
tracedraw-cdr.workspace = true
tracedraw-io.workspace = true
kurbo.workspace = true
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
log.workspace = true
env_logger.workspace = true
